search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAH0YMQEAAAAAOEcvqi8zpsrNzeoxgrtYqTSzoCs%3DEF8ZqxWwqWKAY2Rnn5rpW6uHpzHh8CdbVoyUIWB1eXMqrWnphF
azure:
  subscription_key: 2fc42923-0c81-4ed0-bd8a-8351dcb2945c